#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER laravel
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

#/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
exec php-fpm
